import dhg

g = dhg.BiGraph.from_adj_list(5, 4, [(0, 3, 2), (4, 2, 0), (1, 1, 2)])
print(g)
print(g.e)
print("0" * 100)
print(g.B.to_dense())
print("1" * 100)
print(g.A.to_dense())
print("2" * 100)
hg = dhg.Hypergraph(5, [(0, 1, 2), (1, 3, 2), (1, 2), (0, 3, 4)])
print(hg.e)
print("3" * 100)
print(hg.H.to_dense())
# Construct a bipartite graph from hypergraph
g = dhg.BiGraph.from_hypergraph(hg, vertex_as_U=True)
print("4" * 100)
print(g.e)
print("5" * 100)
print(g.B.to_dense())
print("6" * 100)
g = dhg.BiGraph.from_hypergraph(hg, vertex_as_U=False)
print(g)
print(g.e)
print("7" * 100)
print(g.B.to_dense())
