import dhg

g = dhg.Graph(5, [(0, 1), (1, 2), (2, 3), (1, 4)])
print(g)
print(g.e)
print(g.A.to_dense())
print("1" * 100)
hg = dhg.Hypergraph.from_graph(g)
print(hg.e)
print(hg.H.to_dense())
print("2" * 100)
g = dhg.Graph(5, [(0, 1), (1, 2), (2, 3), (1, 4)])
print(g.e)
print("3" * 100)
print(g.A.to_dense())
hg = dhg.Hypergraph.from_graph_kHop(g, k=1)
print("4" * 100)
print(hg.e)
print("5" * 100)
print(hg.H.to_dense())
print("6" * 100)
print(hg.H)

print("7" * 100)
hg = dhg.Hypergraph.from_graph_kHop(g, k=2)
print(hg.e)
print("8" * 100)
print(hg.H.to_dense())
